version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      development:
        dependency-type: development
      polkadot-api:
        patterns:
          - "@polkadot-api/*"
          - polkadot-api
      reactive-dot:
        patterns:
          - "@reactive-dot/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
