/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutQueriesRouteImport } from './routes/_layout/queries'
import { Route as LayoutExtrinsicsRouteImport } from './routes/_layout/extrinsics'
import { Route as LayoutExplorerRouteImport } from './routes/_layout/explorer'
import { Route as LayoutNoCustomRouteImport } from './routes/_layout/_no-custom'
import { Route as LayoutUtilitiesIndexRouteImport } from './routes/_layout/utilities/index'
import { Route as LayoutUtilitiesLayoutRouteImport } from './routes/_layout/utilities/_layout'
import { Route as LayoutAccountsLayoutRouteImport } from './routes/_layout/accounts/_layout'
import { Route as LayoutNoCustomAssetsRouteImport } from './routes/_layout/_no-custom/assets'
import { Route as LayoutAccountsLayoutIndexRouteImport } from './routes/_layout/accounts/_layout/index'
import { Route as LayoutNoCustomStakingIndexRouteImport } from './routes/_layout/_no-custom/staking/index'
import { Route as LayoutNoCustomReferendaIndexRouteImport } from './routes/_layout/_no-custom/referenda/index'
import { Route as LayoutNoCustomCollectivesIndexRouteImport } from './routes/_layout/_no-custom/collectives/index'
import { Route as LayoutUtilitiesLayoutPlanckConvertorRouteImport } from './routes/_layout/utilities/_layout/planck-convertor'
import { Route as LayoutAccountsLayoutValidatorsRouteImport } from './routes/_layout/accounts/_layout/validators'
import { Route as LayoutNoCustomStakingLayoutRouteImport } from './routes/_layout/_no-custom/staking/_layout'
import { Route as LayoutNoCustomCollectivesLayoutRouteImport } from './routes/_layout/_no-custom/collectives/_layout'
import { Route as LayoutNoCustomStakingLayoutValidatorsRouteImport } from './routes/_layout/_no-custom/staking/_layout/validators'
import { Route as LayoutNoCustomStakingLayoutNominationPoolsRouteImport } from './routes/_layout/_no-custom/staking/_layout/nomination-pools'
import { Route as LayoutNoCustomCollectivesLayoutFellowshipRouteImport } from './routes/_layout/_no-custom/collectives/_layout/fellowship'
import { Route as LayoutNoCustomCollectivesLayoutAmbassadorRouteImport } from './routes/_layout/_no-custom/collectives/_layout/ambassador'

const LayoutUtilitiesRouteImport = createFileRoute('/_layout/utilities')()
const LayoutAccountsRouteImport = createFileRoute('/_layout/accounts')()
const LayoutNoCustomStakingRouteImport = createFileRoute(
  '/_layout/_no-custom/staking',
)()
const LayoutNoCustomCollectivesRouteImport = createFileRoute(
  '/_layout/_no-custom/collectives',
)()

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUtilitiesRoute = LayoutUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountsRoute = LayoutAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQueriesRoute = LayoutQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExtrinsicsRoute = LayoutExtrinsicsRouteImport.update({
  id: '/extrinsics',
  path: '/extrinsics',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExplorerRoute = LayoutExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNoCustomRoute = LayoutNoCustomRouteImport.update({
  id: '/_no-custom',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNoCustomStakingRoute = LayoutNoCustomStakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => LayoutNoCustomRoute,
} as any)
const LayoutNoCustomCollectivesRoute =
  LayoutNoCustomCollectivesRouteImport.update({
    id: '/collectives',
    path: '/collectives',
    getParentRoute: () => LayoutNoCustomRoute,
  } as any)
const LayoutUtilitiesIndexRoute = LayoutUtilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutUtilitiesRoute,
} as any)
const LayoutUtilitiesLayoutRoute = LayoutUtilitiesLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutUtilitiesRoute,
} as any)
const LayoutAccountsLayoutRoute = LayoutAccountsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutAccountsRoute,
} as any)
const LayoutNoCustomAssetsRoute = LayoutNoCustomAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => LayoutNoCustomRoute,
} as any)
const LayoutAccountsLayoutIndexRoute =
  LayoutAccountsLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAccountsLayoutRoute,
  } as any)
const LayoutNoCustomStakingIndexRoute =
  LayoutNoCustomStakingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutNoCustomStakingRoute,
  } as any)
const LayoutNoCustomReferendaIndexRoute =
  LayoutNoCustomReferendaIndexRouteImport.update({
    id: '/referenda/',
    path: '/referenda/',
    getParentRoute: () => LayoutNoCustomRoute,
  } as any)
const LayoutNoCustomCollectivesIndexRoute =
  LayoutNoCustomCollectivesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutNoCustomCollectivesRoute,
  } as any)
const LayoutUtilitiesLayoutPlanckConvertorRoute =
  LayoutUtilitiesLayoutPlanckConvertorRouteImport.update({
    id: '/planck-convertor',
    path: '/planck-convertor',
    getParentRoute: () => LayoutUtilitiesLayoutRoute,
  } as any)
const LayoutAccountsLayoutValidatorsRoute =
  LayoutAccountsLayoutValidatorsRouteImport.update({
    id: '/validators',
    path: '/validators',
    getParentRoute: () => LayoutAccountsLayoutRoute,
  } as any)
const LayoutNoCustomStakingLayoutRoute =
  LayoutNoCustomStakingLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutNoCustomStakingRoute,
  } as any)
const LayoutNoCustomCollectivesLayoutRoute =
  LayoutNoCustomCollectivesLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutNoCustomCollectivesRoute,
  } as any)
const LayoutNoCustomStakingLayoutValidatorsRoute =
  LayoutNoCustomStakingLayoutValidatorsRouteImport.update({
    id: '/validators',
    path: '/validators',
    getParentRoute: () => LayoutNoCustomStakingLayoutRoute,
  } as any)
const LayoutNoCustomStakingLayoutNominationPoolsRoute =
  LayoutNoCustomStakingLayoutNominationPoolsRouteImport.update({
    id: '/nomination-pools',
    path: '/nomination-pools',
    getParentRoute: () => LayoutNoCustomStakingLayoutRoute,
  } as any)
const LayoutNoCustomCollectivesLayoutFellowshipRoute =
  LayoutNoCustomCollectivesLayoutFellowshipRouteImport.update({
    id: '/fellowship',
    path: '/fellowship',
    getParentRoute: () => LayoutNoCustomCollectivesLayoutRoute,
  } as any)
const LayoutNoCustomCollectivesLayoutAmbassadorRoute =
  LayoutNoCustomCollectivesLayoutAmbassadorRouteImport.update({
    id: '/ambassador',
    path: '/ambassador',
    getParentRoute: () => LayoutNoCustomCollectivesLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer': typeof LayoutExplorerRoute
  '/extrinsics': typeof LayoutExtrinsicsRoute
  '/queries': typeof LayoutQueriesRoute
  '/assets': typeof LayoutNoCustomAssetsRoute
  '/accounts': typeof LayoutAccountsLayoutRouteWithChildren
  '/utilities': typeof LayoutUtilitiesLayoutRouteWithChildren
  '/utilities/': typeof LayoutUtilitiesIndexRoute
  '/collectives': typeof LayoutNoCustomCollectivesLayoutRouteWithChildren
  '/staking': typeof LayoutNoCustomStakingLayoutRouteWithChildren
  '/accounts/validators': typeof LayoutAccountsLayoutValidatorsRoute
  '/utilities/planck-convertor': typeof LayoutUtilitiesLayoutPlanckConvertorRoute
  '/collectives/': typeof LayoutNoCustomCollectivesIndexRoute
  '/referenda': typeof LayoutNoCustomReferendaIndexRoute
  '/staking/': typeof LayoutNoCustomStakingIndexRoute
  '/accounts/': typeof LayoutAccountsLayoutIndexRoute
  '/collectives/ambassador': typeof LayoutNoCustomCollectivesLayoutAmbassadorRoute
  '/collectives/fellowship': typeof LayoutNoCustomCollectivesLayoutFellowshipRoute
  '/staking/nomination-pools': typeof LayoutNoCustomStakingLayoutNominationPoolsRoute
  '/staking/validators': typeof LayoutNoCustomStakingLayoutValidatorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof LayoutExplorerRoute
  '/extrinsics': typeof LayoutExtrinsicsRoute
  '/queries': typeof LayoutQueriesRoute
  '/assets': typeof LayoutNoCustomAssetsRoute
  '/accounts': typeof LayoutAccountsLayoutIndexRoute
  '/utilities': typeof LayoutUtilitiesIndexRoute
  '/collectives': typeof LayoutNoCustomCollectivesIndexRoute
  '/staking': typeof LayoutNoCustomStakingIndexRoute
  '/accounts/validators': typeof LayoutAccountsLayoutValidatorsRoute
  '/utilities/planck-convertor': typeof LayoutUtilitiesLayoutPlanckConvertorRoute
  '/referenda': typeof LayoutNoCustomReferendaIndexRoute
  '/collectives/ambassador': typeof LayoutNoCustomCollectivesLayoutAmbassadorRoute
  '/collectives/fellowship': typeof LayoutNoCustomCollectivesLayoutFellowshipRoute
  '/staking/nomination-pools': typeof LayoutNoCustomStakingLayoutNominationPoolsRoute
  '/staking/validators': typeof LayoutNoCustomStakingLayoutValidatorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_no-custom': typeof LayoutNoCustomRouteWithChildren
  '/_layout/explorer': typeof LayoutExplorerRoute
  '/_layout/extrinsics': typeof LayoutExtrinsicsRoute
  '/_layout/queries': typeof LayoutQueriesRoute
  '/_layout/_no-custom/assets': typeof LayoutNoCustomAssetsRoute
  '/_layout/accounts': typeof LayoutAccountsRouteWithChildren
  '/_layout/accounts/_layout': typeof LayoutAccountsLayoutRouteWithChildren
  '/_layout/utilities': typeof LayoutUtilitiesRouteWithChildren
  '/_layout/utilities/_layout': typeof LayoutUtilitiesLayoutRouteWithChildren
  '/_layout/utilities/': typeof LayoutUtilitiesIndexRoute
  '/_layout/_no-custom/collectives': typeof LayoutNoCustomCollectivesRouteWithChildren
  '/_layout/_no-custom/collectives/_layout': typeof LayoutNoCustomCollectivesLayoutRouteWithChildren
  '/_layout/_no-custom/staking': typeof LayoutNoCustomStakingRouteWithChildren
  '/_layout/_no-custom/staking/_layout': typeof LayoutNoCustomStakingLayoutRouteWithChildren
  '/_layout/accounts/_layout/validators': typeof LayoutAccountsLayoutValidatorsRoute
  '/_layout/utilities/_layout/planck-convertor': typeof LayoutUtilitiesLayoutPlanckConvertorRoute
  '/_layout/_no-custom/collectives/': typeof LayoutNoCustomCollectivesIndexRoute
  '/_layout/_no-custom/referenda/': typeof LayoutNoCustomReferendaIndexRoute
  '/_layout/_no-custom/staking/': typeof LayoutNoCustomStakingIndexRoute
  '/_layout/accounts/_layout/': typeof LayoutAccountsLayoutIndexRoute
  '/_layout/_no-custom/collectives/_layout/ambassador': typeof LayoutNoCustomCollectivesLayoutAmbassadorRoute
  '/_layout/_no-custom/collectives/_layout/fellowship': typeof LayoutNoCustomCollectivesLayoutFellowshipRoute
  '/_layout/_no-custom/staking/_layout/nomination-pools': typeof LayoutNoCustomStakingLayoutNominationPoolsRoute
  '/_layout/_no-custom/staking/_layout/validators': typeof LayoutNoCustomStakingLayoutValidatorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explorer'
    | '/extrinsics'
    | '/queries'
    | '/assets'
    | '/accounts'
    | '/utilities'
    | '/utilities/'
    | '/collectives'
    | '/staking'
    | '/accounts/validators'
    | '/utilities/planck-convertor'
    | '/collectives/'
    | '/referenda'
    | '/staking/'
    | '/accounts/'
    | '/collectives/ambassador'
    | '/collectives/fellowship'
    | '/staking/nomination-pools'
    | '/staking/validators'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorer'
    | '/extrinsics'
    | '/queries'
    | '/assets'
    | '/accounts'
    | '/utilities'
    | '/collectives'
    | '/staking'
    | '/accounts/validators'
    | '/utilities/planck-convertor'
    | '/referenda'
    | '/collectives/ambassador'
    | '/collectives/fellowship'
    | '/staking/nomination-pools'
    | '/staking/validators'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/_no-custom'
    | '/_layout/explorer'
    | '/_layout/extrinsics'
    | '/_layout/queries'
    | '/_layout/_no-custom/assets'
    | '/_layout/accounts'
    | '/_layout/accounts/_layout'
    | '/_layout/utilities'
    | '/_layout/utilities/_layout'
    | '/_layout/utilities/'
    | '/_layout/_no-custom/collectives'
    | '/_layout/_no-custom/collectives/_layout'
    | '/_layout/_no-custom/staking'
    | '/_layout/_no-custom/staking/_layout'
    | '/_layout/accounts/_layout/validators'
    | '/_layout/utilities/_layout/planck-convertor'
    | '/_layout/_no-custom/collectives/'
    | '/_layout/_no-custom/referenda/'
    | '/_layout/_no-custom/staking/'
    | '/_layout/accounts/_layout/'
    | '/_layout/_no-custom/collectives/_layout/ambassador'
    | '/_layout/_no-custom/collectives/_layout/fellowship'
    | '/_layout/_no-custom/staking/_layout/nomination-pools'
    | '/_layout/_no-custom/staking/_layout/validators'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/utilities': {
      id: '/_layout/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof LayoutUtilitiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/accounts': {
      id: '/_layout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/queries': {
      id: '/_layout/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof LayoutQueriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/extrinsics': {
      id: '/_layout/extrinsics'
      path: '/extrinsics'
      fullPath: '/extrinsics'
      preLoaderRoute: typeof LayoutExtrinsicsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explorer': {
      id: '/_layout/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof LayoutExplorerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_no-custom': {
      id: '/_layout/_no-custom'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutNoCustomRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_no-custom/staking': {
      id: '/_layout/_no-custom/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof LayoutNoCustomStakingRouteImport
      parentRoute: typeof LayoutNoCustomRoute
    }
    '/_layout/_no-custom/collectives': {
      id: '/_layout/_no-custom/collectives'
      path: '/collectives'
      fullPath: '/collectives'
      preLoaderRoute: typeof LayoutNoCustomCollectivesRouteImport
      parentRoute: typeof LayoutNoCustomRoute
    }
    '/_layout/utilities/': {
      id: '/_layout/utilities/'
      path: '/'
      fullPath: '/utilities/'
      preLoaderRoute: typeof LayoutUtilitiesIndexRouteImport
      parentRoute: typeof LayoutUtilitiesRoute
    }
    '/_layout/utilities/_layout': {
      id: '/_layout/utilities/_layout'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof LayoutUtilitiesLayoutRouteImport
      parentRoute: typeof LayoutUtilitiesRoute
    }
    '/_layout/accounts/_layout': {
      id: '/_layout/accounts/_layout'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsLayoutRouteImport
      parentRoute: typeof LayoutAccountsRoute
    }
    '/_layout/_no-custom/assets': {
      id: '/_layout/_no-custom/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof LayoutNoCustomAssetsRouteImport
      parentRoute: typeof LayoutNoCustomRoute
    }
    '/_layout/accounts/_layout/': {
      id: '/_layout/accounts/_layout/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof LayoutAccountsLayoutIndexRouteImport
      parentRoute: typeof LayoutAccountsLayoutRoute
    }
    '/_layout/_no-custom/staking/': {
      id: '/_layout/_no-custom/staking/'
      path: '/'
      fullPath: '/staking/'
      preLoaderRoute: typeof LayoutNoCustomStakingIndexRouteImport
      parentRoute: typeof LayoutNoCustomStakingRoute
    }
    '/_layout/_no-custom/referenda/': {
      id: '/_layout/_no-custom/referenda/'
      path: '/referenda'
      fullPath: '/referenda'
      preLoaderRoute: typeof LayoutNoCustomReferendaIndexRouteImport
      parentRoute: typeof LayoutNoCustomRoute
    }
    '/_layout/_no-custom/collectives/': {
      id: '/_layout/_no-custom/collectives/'
      path: '/'
      fullPath: '/collectives/'
      preLoaderRoute: typeof LayoutNoCustomCollectivesIndexRouteImport
      parentRoute: typeof LayoutNoCustomCollectivesRoute
    }
    '/_layout/utilities/_layout/planck-convertor': {
      id: '/_layout/utilities/_layout/planck-convertor'
      path: '/planck-convertor'
      fullPath: '/utilities/planck-convertor'
      preLoaderRoute: typeof LayoutUtilitiesLayoutPlanckConvertorRouteImport
      parentRoute: typeof LayoutUtilitiesLayoutRoute
    }
    '/_layout/accounts/_layout/validators': {
      id: '/_layout/accounts/_layout/validators'
      path: '/validators'
      fullPath: '/accounts/validators'
      preLoaderRoute: typeof LayoutAccountsLayoutValidatorsRouteImport
      parentRoute: typeof LayoutAccountsLayoutRoute
    }
    '/_layout/_no-custom/staking/_layout': {
      id: '/_layout/_no-custom/staking/_layout'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof LayoutNoCustomStakingLayoutRouteImport
      parentRoute: typeof LayoutNoCustomStakingRoute
    }
    '/_layout/_no-custom/collectives/_layout': {
      id: '/_layout/_no-custom/collectives/_layout'
      path: '/collectives'
      fullPath: '/collectives'
      preLoaderRoute: typeof LayoutNoCustomCollectivesLayoutRouteImport
      parentRoute: typeof LayoutNoCustomCollectivesRoute
    }
    '/_layout/_no-custom/staking/_layout/validators': {
      id: '/_layout/_no-custom/staking/_layout/validators'
      path: '/validators'
      fullPath: '/staking/validators'
      preLoaderRoute: typeof LayoutNoCustomStakingLayoutValidatorsRouteImport
      parentRoute: typeof LayoutNoCustomStakingLayoutRoute
    }
    '/_layout/_no-custom/staking/_layout/nomination-pools': {
      id: '/_layout/_no-custom/staking/_layout/nomination-pools'
      path: '/nomination-pools'
      fullPath: '/staking/nomination-pools'
      preLoaderRoute: typeof LayoutNoCustomStakingLayoutNominationPoolsRouteImport
      parentRoute: typeof LayoutNoCustomStakingLayoutRoute
    }
    '/_layout/_no-custom/collectives/_layout/fellowship': {
      id: '/_layout/_no-custom/collectives/_layout/fellowship'
      path: '/fellowship'
      fullPath: '/collectives/fellowship'
      preLoaderRoute: typeof LayoutNoCustomCollectivesLayoutFellowshipRouteImport
      parentRoute: typeof LayoutNoCustomCollectivesLayoutRoute
    }
    '/_layout/_no-custom/collectives/_layout/ambassador': {
      id: '/_layout/_no-custom/collectives/_layout/ambassador'
      path: '/ambassador'
      fullPath: '/collectives/ambassador'
      preLoaderRoute: typeof LayoutNoCustomCollectivesLayoutAmbassadorRouteImport
      parentRoute: typeof LayoutNoCustomCollectivesLayoutRoute
    }
  }
}

interface LayoutNoCustomCollectivesLayoutRouteChildren {
  LayoutNoCustomCollectivesLayoutAmbassadorRoute: typeof LayoutNoCustomCollectivesLayoutAmbassadorRoute
  LayoutNoCustomCollectivesLayoutFellowshipRoute: typeof LayoutNoCustomCollectivesLayoutFellowshipRoute
}

const LayoutNoCustomCollectivesLayoutRouteChildren: LayoutNoCustomCollectivesLayoutRouteChildren =
  {
    LayoutNoCustomCollectivesLayoutAmbassadorRoute:
      LayoutNoCustomCollectivesLayoutAmbassadorRoute,
    LayoutNoCustomCollectivesLayoutFellowshipRoute:
      LayoutNoCustomCollectivesLayoutFellowshipRoute,
  }

const LayoutNoCustomCollectivesLayoutRouteWithChildren =
  LayoutNoCustomCollectivesLayoutRoute._addFileChildren(
    LayoutNoCustomCollectivesLayoutRouteChildren,
  )

interface LayoutNoCustomCollectivesRouteChildren {
  LayoutNoCustomCollectivesLayoutRoute: typeof LayoutNoCustomCollectivesLayoutRouteWithChildren
  LayoutNoCustomCollectivesIndexRoute: typeof LayoutNoCustomCollectivesIndexRoute
}

const LayoutNoCustomCollectivesRouteChildren: LayoutNoCustomCollectivesRouteChildren =
  {
    LayoutNoCustomCollectivesLayoutRoute:
      LayoutNoCustomCollectivesLayoutRouteWithChildren,
    LayoutNoCustomCollectivesIndexRoute: LayoutNoCustomCollectivesIndexRoute,
  }

const LayoutNoCustomCollectivesRouteWithChildren =
  LayoutNoCustomCollectivesRoute._addFileChildren(
    LayoutNoCustomCollectivesRouteChildren,
  )

interface LayoutNoCustomStakingLayoutRouteChildren {
  LayoutNoCustomStakingLayoutNominationPoolsRoute: typeof LayoutNoCustomStakingLayoutNominationPoolsRoute
  LayoutNoCustomStakingLayoutValidatorsRoute: typeof LayoutNoCustomStakingLayoutValidatorsRoute
}

const LayoutNoCustomStakingLayoutRouteChildren: LayoutNoCustomStakingLayoutRouteChildren =
  {
    LayoutNoCustomStakingLayoutNominationPoolsRoute:
      LayoutNoCustomStakingLayoutNominationPoolsRoute,
    LayoutNoCustomStakingLayoutValidatorsRoute:
      LayoutNoCustomStakingLayoutValidatorsRoute,
  }

const LayoutNoCustomStakingLayoutRouteWithChildren =
  LayoutNoCustomStakingLayoutRoute._addFileChildren(
    LayoutNoCustomStakingLayoutRouteChildren,
  )

interface LayoutNoCustomStakingRouteChildren {
  LayoutNoCustomStakingLayoutRoute: typeof LayoutNoCustomStakingLayoutRouteWithChildren
  LayoutNoCustomStakingIndexRoute: typeof LayoutNoCustomStakingIndexRoute
}

const LayoutNoCustomStakingRouteChildren: LayoutNoCustomStakingRouteChildren = {
  LayoutNoCustomStakingLayoutRoute:
    LayoutNoCustomStakingLayoutRouteWithChildren,
  LayoutNoCustomStakingIndexRoute: LayoutNoCustomStakingIndexRoute,
}

const LayoutNoCustomStakingRouteWithChildren =
  LayoutNoCustomStakingRoute._addFileChildren(
    LayoutNoCustomStakingRouteChildren,
  )

interface LayoutNoCustomRouteChildren {
  LayoutNoCustomAssetsRoute: typeof LayoutNoCustomAssetsRoute
  LayoutNoCustomCollectivesRoute: typeof LayoutNoCustomCollectivesRouteWithChildren
  LayoutNoCustomStakingRoute: typeof LayoutNoCustomStakingRouteWithChildren
  LayoutNoCustomReferendaIndexRoute: typeof LayoutNoCustomReferendaIndexRoute
}

const LayoutNoCustomRouteChildren: LayoutNoCustomRouteChildren = {
  LayoutNoCustomAssetsRoute: LayoutNoCustomAssetsRoute,
  LayoutNoCustomCollectivesRoute: LayoutNoCustomCollectivesRouteWithChildren,
  LayoutNoCustomStakingRoute: LayoutNoCustomStakingRouteWithChildren,
  LayoutNoCustomReferendaIndexRoute: LayoutNoCustomReferendaIndexRoute,
}

const LayoutNoCustomRouteWithChildren = LayoutNoCustomRoute._addFileChildren(
  LayoutNoCustomRouteChildren,
)

interface LayoutAccountsLayoutRouteChildren {
  LayoutAccountsLayoutValidatorsRoute: typeof LayoutAccountsLayoutValidatorsRoute
  LayoutAccountsLayoutIndexRoute: typeof LayoutAccountsLayoutIndexRoute
}

const LayoutAccountsLayoutRouteChildren: LayoutAccountsLayoutRouteChildren = {
  LayoutAccountsLayoutValidatorsRoute: LayoutAccountsLayoutValidatorsRoute,
  LayoutAccountsLayoutIndexRoute: LayoutAccountsLayoutIndexRoute,
}

const LayoutAccountsLayoutRouteWithChildren =
  LayoutAccountsLayoutRoute._addFileChildren(LayoutAccountsLayoutRouteChildren)

interface LayoutAccountsRouteChildren {
  LayoutAccountsLayoutRoute: typeof LayoutAccountsLayoutRouteWithChildren
}

const LayoutAccountsRouteChildren: LayoutAccountsRouteChildren = {
  LayoutAccountsLayoutRoute: LayoutAccountsLayoutRouteWithChildren,
}

const LayoutAccountsRouteWithChildren = LayoutAccountsRoute._addFileChildren(
  LayoutAccountsRouteChildren,
)

interface LayoutUtilitiesLayoutRouteChildren {
  LayoutUtilitiesLayoutPlanckConvertorRoute: typeof LayoutUtilitiesLayoutPlanckConvertorRoute
}

const LayoutUtilitiesLayoutRouteChildren: LayoutUtilitiesLayoutRouteChildren = {
  LayoutUtilitiesLayoutPlanckConvertorRoute:
    LayoutUtilitiesLayoutPlanckConvertorRoute,
}

const LayoutUtilitiesLayoutRouteWithChildren =
  LayoutUtilitiesLayoutRoute._addFileChildren(
    LayoutUtilitiesLayoutRouteChildren,
  )

interface LayoutUtilitiesRouteChildren {
  LayoutUtilitiesLayoutRoute: typeof LayoutUtilitiesLayoutRouteWithChildren
  LayoutUtilitiesIndexRoute: typeof LayoutUtilitiesIndexRoute
}

const LayoutUtilitiesRouteChildren: LayoutUtilitiesRouteChildren = {
  LayoutUtilitiesLayoutRoute: LayoutUtilitiesLayoutRouteWithChildren,
  LayoutUtilitiesIndexRoute: LayoutUtilitiesIndexRoute,
}

const LayoutUtilitiesRouteWithChildren = LayoutUtilitiesRoute._addFileChildren(
  LayoutUtilitiesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutNoCustomRoute: typeof LayoutNoCustomRouteWithChildren
  LayoutExplorerRoute: typeof LayoutExplorerRoute
  LayoutExtrinsicsRoute: typeof LayoutExtrinsicsRoute
  LayoutQueriesRoute: typeof LayoutQueriesRoute
  LayoutAccountsRoute: typeof LayoutAccountsRouteWithChildren
  LayoutUtilitiesRoute: typeof LayoutUtilitiesRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutNoCustomRoute: LayoutNoCustomRouteWithChildren,
  LayoutExplorerRoute: LayoutExplorerRoute,
  LayoutExtrinsicsRoute: LayoutExtrinsicsRoute,
  LayoutQueriesRoute: LayoutQueriesRoute,
  LayoutAccountsRoute: LayoutAccountsRouteWithChildren,
  LayoutUtilitiesRoute: LayoutUtilitiesRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
