name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-node/issues/899
      - run: corepack enable
        shell: bash

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: yarn

      - run: yarn install --immutable
        shell: bash

      - run: yarn build

      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dot-console
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
