name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4

      - run: yarn install --immutable
        shell: bash

      - run: yarn build

      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: dot-console
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
